# inherit_from:
# - rubocop-todo.yml

LineLength:
  Enabled: false

HashSyntax:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

BlockNesting:
  Enabled: false

AssignmentInCondition:
  Enabled: false

CollectionMethods:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

MethodLength:
  Enabled: false

PerlBackrefs:
  Enabled: false

RescueModifier:
  Enabled: false

SuppressedException:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  ExcludedMethods:
    - class_methods
    - included
  Exclude:
    - test/**/*
    - bin/**/*

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - test/**/*
    - bin/**/*

Metrics/ModuleLength:
  Enabled: true
  Exclude:
    - test/**/*
    - bin/**/*
